spring:
  application:
    name: ToDoListProj

  datasource:
    url: jdbc:h2:tcp://localhost/~/todolist
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    show-sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace